name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install buildifier
      run: |
        curl -L https://github.com/bazelbuild/buildtools/releases/latest/download/buildifier-linux-amd64 -o buildifier
        chmod +x buildifier
        sudo mv buildifier /usr/local/bin/

    - name: Check Bazel/Starlark formatting
      run: |
        echo "Checking BUILD.bazel and .bzl file formatting..."
        # Find all Bazel/Starlark files (excluding bazel- output directories)
        FILES=$(find . -name "BUILD.bazel" -o -name "*.bzl" | grep -v bazel-)

        # Check if files are properly formatted
        if ! buildifier --lint=warn --mode=check $FILES; then
          echo "❌ Formatting issues found! Run the following to fix:"
          echo "buildifier --lint=fix $FILES"
          exit 1
        fi
        echo "✅ All Bazel/Starlark files are properly formatted"

  test:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y rpm-build rpm-devel gtk4-devel gcc-c++ git dnf-plugins-core rpmlint
        dnf copr enable -y lihaohong/bazel
        dnf install -y bazel

    - name: Test simple binary example
      run: |
        echo "=== Building simple binary RPM ==="
        bazel build //examples/simple_binary:hello_world_rpm
        echo "=== Testing RPM contents ==="
        rpm -qpil bazel-bin/examples/simple_binary/hello_world_rpm.rpm
        echo "=== Running rpmlint ==="
        rpmlint bazel-bin/examples/simple_binary/hello_world_rpm.rpm

    - name: Test complex package example (direct headers)
      run: |
        echo "=== Building complex package RPM (direct headers) ==="
        bazel build //examples/complex_package:complex_app_rpm
        echo "=== Testing RPM contents ==="
        rpm -qp --requires bazel-bin/examples/complex_package/complex_app_rpm.rpm
        echo "=== Running rpmlint ==="
        rpmlint bazel-bin/examples/complex_package/complex_app_rpm.rpm

    - name: Test complex package example (transitive headers)
      run: |
        echo "=== Building complex package RPM (transitive headers) ==="
        bazel build //examples/complex_package:complex_app_rpm_with_transitive
        echo "=== Testing RPM contents ==="
        rpm -qp --requires bazel-bin/examples/complex_package/complex_app_rpm_with_transitive.rpm
        echo "=== Running rpmlint ==="
        rpmlint bazel-bin/examples/complex_package/complex_app_rpm_with_transitive.rpm

    - name: Test GTK example
      run: |
        echo "=== Building GTK example RPM ==="
        bazel build //examples/gtk_example:gtk_app_rpm
        echo "=== Testing RPM contents ==="
        rpm -qp --requires bazel-bin/examples/gtk_example/gtk_app_rpm.rpm
        echo "=== Running rpmlint ==="
        rpmlint bazel-bin/examples/gtk_example/gtk_app_rpm.rpm
