name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y rpm-build rpm-devel gtk4-devel gcc-c++ git dnf-plugins-core
        dnf copr enable -y lihaohong/bazel
        dnf install -y bazel

    - name: Build examples
      run: |
        bazel build //examples/simple_binary:hello_world_rpm
        bazel build //examples/complex_package:complex_app_rpm
        bazel build //examples/gtk_example:gtk_app_rpm

    - name: Run tests
      run: bazel test //tests/...

    - name: Test RPM contents
      run: |
        rpm -qpil bazel-bin/examples/simple_binary/hello_world_rpm.rpm
        rpm -qp --requires bazel-bin/examples/complex_package/complex_app_rpm.rpm