name: Publish to BCR

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v6
    with:
      tag_name: ${{ inputs.tag_name }}
      registry_fork: bilelmoussaoui/bazel-central-registry
      attest: true
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}