name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g. v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write
  actions: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.3
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      bazel_test_command: bazel build //examples/simple_binary/... //examples/complex_package/... //rpm/... //toolchains/...
      release_files: rules_rpm-*.tar.gz
      prerelease: false

  trigger_publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger publish workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish.yml',
              ref: 'main',
              inputs: {
                tag_name: '${{ inputs.tag_name || github.ref_name }}'
              }
            })
