name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  release:
    uses: bazel-contrib/release_ruleset/.github/workflows/release_ruleset.yaml@v1
    with:
      tag_name: ${{ inputs.tag_name }}
      attest: true
    permissions:
      contents: write
      id-token: write
      attestations: write