name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.3
    with:
      tag_name: ${{ inputs.tag_name }}
      release_files: |
        MODULE.bazel
        metadata.json
        presubmit.yml
        .bcr/**
    permissions:
      contents: write
      id-token: write
      attestations: write
